### ISSUE TITLE
S3 static website hosting config reverts / permission issues

### ISSUE THREAD

**Issue by pushred** [SparkartGroupInc/qa-deployer#12]
There's definitely some problems with S3 deploys, probably originating in https://github.com/firstopinion/s3-site. Recently for one bucket the Static Website Hosting options have gotten disabled/reverted twice following deploys, resulting in this:

```
404 Not Found

Code: NoSuchWebsiteConfiguration
Message: The specified bucket does not have a website configuration
BucketName: www.example.com
RequestId: 442FC3669C9F8909
HostId: 6hgxudT9Pu0ZMn0V8/ZisfCwv7WV2vwPzQxO8jPSnA42ifGOR6PsGgOemgJLM3Ta
```

Then in other instances permissions get into a weird state:

```
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: 79874C1B5CBE2E40
HostId: XtCSdSxxgySIs4YsTBB623lXZ8yb1B+yFU7ASGuK+UUKjZIcpkgLrIavRQYsiHV6aJrd/zkF+gQ=
```

Seeing this after a deploy just now I retried the deploy and initially got the errors again. But after a few page reloads it seems fine. Perhaps the module is upload to S3 too quickly?

**Comment by joanniclaborde** [comment]
No error ever happens during the actual deploy? I looked at s3-site's code, and everything looks fine. The only thing that could break is the `deleteBucket` call; it fails if the bucket is not empty, and it could happen if it contained more than 1000 objects, since `listObjects`/`deleteObjects` are limited to 1000. But a failing `deleteBucket` would stop the deploy anyway.

I'll update s3-site to use the latest aws-sdk version, and we'll see if that fixes our problems.

**Comment by pushred** [comment]
Not that I've seen, see the logs on the builds, here's the one with the 404 error:

https://circleci.com/gh/SparkartGroupInc/brandonflowersmusic.com/26

Is there any logging from s3-site that you could expose?

**Comment by joanniclaborde** [comment]
No s3-site doesn't log anything. I updated it to use the latest aws-sdk, and released those changes as 2.1.1. Let's see if this fixes our problem... :(

**Comment by pushred** [comment]
Just ran into the 404 error again with 2.1.1

**Comment by pushred** [comment]
Still happening. If the issue lies within S3 or if there's no movement on addressing it within the node SDK then maybe we need to accommodate failure. What about making a request to the deployed site post-deploy to do a health check? If it's 200, then the deploy is successful. If it's 4xx or 5xx, retry. Continue to retry until successful (or the build times out).

**Comment by joanniclaborde** [comment]
This is due to Amazon S3's data consistency model. It looks like the operations can be applied out of order. Trying to bypass this issue, that commit doesn't delete an existing bucket when deploying. All operations will be done on an existing bucket, we don't care about the order the operations are applied. Let's hope this issue is closed for good!
